
name: CICD

'on':
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-18.04
    container:
      image: bioconductor/bioconductor_full:devel
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
      - name: Install Package Dependencies
        run: |
          Rscript -e "BiocManager::install(c('remotes', 'rcmdcheck', 'covr', 'pkgdown'))"
          Rscript -e "remotes::install_deps(dependencies = TRUE)"
      - name: System dependencies
        run: |
          sudo apt-get update && apt-get install -y --no-install-recommends \
          texlive-latex-base texlive-fonts-recommended texlive-fonts-extra texlive-latex-extra
          pip install ghp-import
      - name: Check Package
        run: Rscript -e "rcmdcheck::rcmdcheck(error_on = 'error', check_dir = 'check')"
      - name: Document Package
        run: |
          Rscript -e "pkgdown::build_site()"
      - name: Build and Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v2
        env:
          ACCESS_TOKEN: ${{ secrets.GITHUB_PAT }}
          BASE_BRANCH: stripped_down # The branch the action should deploy from.
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: docs # The folder the action should deploy.
          BUILD_SCRIPT: echo 'pushing'
      - name: Deploy to GitHub Pages
        env:
          ACCESS_TOKEN: ${{ secrets.GITHUB_PAT }}
        run: |
          ghp-import -n docs && \
          git push -qf https://seandavi:${ACCESS_TOKEN}@github.com/${GITHUB_REPOSITORY}.git gh-pages
